services:
  postgres:
    image: 'postgres'
    environment:
      - 'POSTGRES_DB=tasks'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    networks:
      - my-network

  springboot-app:
    image: server-side
    container_name: springboot-container
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/tasks'
      SPRING_DATASOURCE_USERNAME: 'myuser'
      SPRING_DATASOURCE_PASSWORD: 'secret'
    volumes:
      - ./target/task-manager-0.0.1-SNAPSHOT.jar:/app/task-manager-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    command: [ "java", "-jar", "/app/task-manager-0.0.1-SNAPSHOT.jar" ]
    networks:
      - my-network

networks:
  my-network:
    driver: bridge